"""Add job_id column to notifications

Revision ID: 62ec6f256d27
Revises: 275fb8d9c75c
Create Date: 2026-01-23 15:43:20.853981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62ec6f256d27'
down_revision: Union[str, Sequence[str], None] = '275fb8d9c75c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('job_id', sa.String(length=32), nullable=True))
    op.alter_column('notifications', 'abstract',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Supplementary context for notification (plan details, URLs, markdown)',
               existing_nullable=True)
    op.alter_column('notifications', 'response_requested',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('idx_notifications_abstract'), table_name='notifications', postgresql_where='(abstract IS NOT NULL)')
    op.drop_index(op.f('idx_notifications_is_hidden'), table_name='notifications')
    op.drop_index(op.f('idx_notifications_type'), table_name='notifications')
    op.drop_index(op.f('idx_notifications_visible_by_sender_date'), table_name='notifications', postgresql_where='(is_hidden = false)')
    op.drop_index(op.f('idx_notifications_created_at'), table_name='notifications')
    op.create_index('idx_notifications_created_at', 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_is_hidden'), 'notifications', ['is_hidden'], unique=False)
    op.create_index(op.f('ix_notifications_job_id'), 'notifications', ['job_id'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_id'), 'notifications', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_notifications_sender_id'), 'notifications', ['sender_id'], unique=False)
    op.create_index(op.f('ix_notifications_state'), 'notifications', ['state'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_state'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_sender_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_recipient_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_job_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_hidden'), table_name='notifications')
    op.drop_index('idx_notifications_created_at', table_name='notifications')
    op.create_index(op.f('idx_notifications_created_at'), 'notifications', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_notifications_visible_by_sender_date'), 'notifications', ['sender_id', 'recipient_id', sa.literal_column('created_at DESC')], unique=False, postgresql_where='(is_hidden = false)')
    op.create_index(op.f('idx_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('idx_notifications_is_hidden'), 'notifications', ['is_hidden'], unique=False)
    op.create_index(op.f('idx_notifications_abstract'), 'notifications', ['abstract'], unique=False, postgresql_where='(abstract IS NOT NULL)')
    op.alter_column('notifications', 'response_requested',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('notifications', 'abstract',
               existing_type=sa.TEXT(),
               comment='Supplementary context for notification (plan details, URLs, markdown)',
               existing_nullable=True)
    op.drop_column('notifications', 'job_id')
    # ### end Alembic commands ###
