// P0 5ebd2aff step 2 — the REAL response_options payloads, for every multiplexer Action Required test.
//
// action_required_questions_payload.json is generated by the server's own builders
// (cosa/utils/notification_utils.py convert_questions_for_api / convert_open_ended_batch_for_api)
// and pinned to them by src/tests/unit/test_multiplexer_questions_fixture_matches_the_asking_tools.py.
// A hand-typed option list is how this client came to believe response_options was string[].
//
// Per case:
//   response_options : what the server puts on the queue update
//   answers          : the answer legacy sends for it — { answers: { <header>: value } }
//   wire_value       : that answer as JSON.stringify writes it, which the Python readers are fed

import { readFileSync } from "node:fs";

import type { ActionRequiredAnswers } from "../../../../lupin_app/static/js/multiplexer/shared/types";

export interface QuestionsPayloadCase {
  questions_in     : unknown;
  response_options : unknown;
  answers          : ActionRequiredAnswers;
  wire_value       : string;
}

export const QUESTIONS_PAYLOAD = JSON.parse(
  readFileSync(new URL("./action_required_questions_payload.json", import.meta.url), "utf8"),
) as { multiple_choice: QuestionsPayloadCase; open_ended_batch: QuestionsPayloadCase };
